### ISSUE TITLE
Crash in 1.0.6 version

### ISSUE THREAD

**Issue by quum** [Quobject/SocketIoClientDotNet#161]
```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
  at System.Collections.Hashtable.Insert(System.Object, System.Object, Boolean)
  at System.Collections.Hashtable.Add(System.Object, System.Object)
  at System.Collections.Specialized.NameObjectCollectionBase.BaseAdd(System.String, System.Object)
  at System.Collections.Specialized.NameValueCollection.Add(System.String, System.String)
  at System.Net.HttpWebRequest.SetSpecialHeaders(System.String, System.String)
  at System.Net.HttpWebRequest.set_ContentType(System.String)
  at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR+XHRRequest.Create()
  at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.DoWrite(Byte[], System.Action)
  at Quobject.EngineIoClientDotNet.Client.Transports.Polling+SendEncodeCallback.Call(System.Object)
  at Quobject.EngineIoClientDotNet.Parser.Packet.EncodePayload(Quobject.EngineIoClientDotNet.Parser.Packet[], Quobject.EngineIoClientDotNet.Parser.IEncodeCallback)
  at Quobject.EngineIoClientDotNet.Client.Transports.Polling.Write(System.Collections.Immutable.ImmutableList`1<Quobject.EngineIoClientDotNet.Parser.Packet>)
  at Quobject.EngineIoClientDotNet.Client.Transport.Send(System.Collections.Immutable.ImmutableList`1<Quobject.EngineIoClientDotNet.Parser.Packet>)
  at Quobject.EngineIoClientDotNet.Client.Socket.Flush()
  at Quobject.EngineIoClientDotNet.Client.Socket.SendPacket(Quobject.EngineIoClientDotNet.Parser.Packet, System.Action)
  at Quobject.EngineIoClientDotNet.Client.Socket.<SetPing>b__65_0()
  at Quobject.EngineIoClientDotNet.Thread.EasyTimer+<>c__DisplayClass2_0.<SetTimeout>b__0()
  at System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(System.Object)
  at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback, System.Object, System.Threading.Tasks.Task ByRef)
  at System.Threading.Tasks.AwaitTaskContinuation+<>c.<ThrowAsyncIfNecessary>b__18_0(System.Object)
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
  at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

We're updating to the 1.0.7.1 version, and we'll see if the same thing happens

**Comment by quum** [comment]
This crash occurs in 1.0.7.1 too, once the service has been running for a number of hours

**Comment by captainjono** [comment]
Im getting the same stacktrace intermittently with 1.0.7.
