### ISSUE TITLE
Error fires on connect every time

### ISSUE THREAD

**Issue by SeanLatimer** [Quobject/SocketIoClientDotNet#86]
Socket.EVENT_CONNECT_ERROR fires on every single connection attempt, regardless of whether the attempt was successful.
The following is the stacktrace produced:

Quobject.EngineIoClientDotNet.Client.EngineIOException: xhr poll error ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.IO.StringReader..ctor(String s)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Quobject.EngineIoClientDotNet.Client.Socket.OnPacket(Packet packet)
   at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Emit(String eventString, Object[] args)
   at Quobject.EngineIoClientDotNet.Client.Transports.Polling.DecodePayloadCallback.Call(Packet packet, Int32 index, Int32 total)
   at Quobject.EngineIoClientDotNet.Parser.Packet.DecodePayload(String data, IDecodePayloadCallback callback)
   at Quobject.EngineIoClientDotNet.Client.Transports.Polling._onData(Object data)
   at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Emit(String eventString, Object[] args)
   at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.OnData(String data)
   at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.<Create>b__7_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.Create()
   --- End of inner exception stack trace ---

**Comment by lorenzo93** [comment]
I have the same bug, I don't know if this issues are correlated but someone with the Java Socket.io client is having the same issue [Here](https://github.com/socketio/socket.io-client-java/issues/250).

Tried to force Upgrade to true but nothing seems to change. 
@SeanLatimer Do you find a workaround or a fix?
